# Generated by Django 5.2.1 on 2025-06-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, help_text="Ordre d'affichage des produits en vedette", null=True),
        ),
    ]
