# Generated by Django 5.2.1 on 2025-06-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='Products_pr_brand_e9a8a5_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='stock_quantity',
        ),
    ]
