# Generated by Django 5.2.1 on 2025-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
