# Generated by Django 5.2.1 on 2025-06-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_productitem_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionproduct',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.promotion'),
        ),
    ]
