# Generated by Django 5.2.1 on 2025-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_promotionproduct_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='variation',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Controls the order of variations (e.g., 0 for Size, 1 for Color)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
