# Generated by Django 5.2.1 on 2025-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationoption',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
