# Generated by Django 5.2.1 on 2025-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_user_addition_details_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=50, null=True),
        ),
    ]
