# Generated by Django 5.2.1 on 2025-06-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
