# Generated by Django 5.2.1 on 2025-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product_sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
