"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b=%e*82*75^kyzo6g*61s)*4ng!ph2h$u7_p&9q-huljy4m-ae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Users',
    'Products',
    'Carts',
    'Orders',
    'Payments',
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # Simple JWT
    'corsheaders',
    'django_countries',
    # 'django_recaptcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'core.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

AUTH_USER_MODEL = 'Users.User'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Clés Google reCAPTCHA
# RECAPTCHA_PUBLIC_KEY = "6Le3XUErAAAAAIEgf-Sp2SAiVPJc6e0vLP16FwBK"
# RECAPTCHA_PRIVATE_KEY = "6Le3XUErAAAAAAY_aTfy57SilY-8czviRlPwJS7D"

# # settings.py

# # settings.py

# # Paramètres de base sécurisés
# SESSION_COOKIE_SECURE = True  # Uniquement via HTTPS
# SESSION_COOKIE_HTTPONLY = True  # Inaccessible via JavaScript
# SESSION_COOKIE_SAMESITE = 'Lax'  # Équilibre sécurité et UX
# SESSION_COOKIE_PATH = '/'  # Accessible sur tout le domaine

# # Protection CSRF
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_PATH = '/'

# Configuration JWT avancée (si vous utilisez djangorestframework-simplejwt)
# JWT_AUTH = {
#     'JWT_AUTH_COOKIE': 'jwt_token',
#     'JWT_AUTH_COOKIE_SECURE': True,
#     'JWT_AUTH_COOKIE_SAMESITE': 'None',  # Nécessaire pour cross-site
#     'JWT_AUTH_COOKIE_PATH': '/',
#     'JWT_AUTH_COOKIE_DOMAIN': None,  # À définir si nécessaire
#     'JWT_AUTH_COOKIE_PARTITIONED': True,  # Nouvel attribut requis pour Chrome
#     'JWT_AUTH_COOKIE_HTTPONLY': True,  # Protection contre XSS
# } # ⚠️ Nécessite HTTPS


# settings.py
PAYPAL_MODE = "sandbox"  # or "live" for production
PAYPAL_CLIENT_ID = "ASC0-9_1T_ego-ldyi_x8OZyYGLr7MV2mufWYTP6CvD5qoBxqB3UriuAig-JIHQi25FXLAAO7JpzjBPx"
PAYPAL_CLIENT_SECRET = "EG80GHK7Nhq9nf9k4SZIvE_JB8D4oRe54sa9ZliPaKaDHOSrv-liTTsI2DLNF0spEKIVwK3jFqr9akjo"


STRIPE_WEBHOOK_SECRET = ""

